# Generated by Django 3.2.5 on 2021-11-30 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CodePlay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='start',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
